name: gamer_stash
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dotlottie_loader: ^0.0.4
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.2
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  provider: ^6.0.5
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/
    - assets/motions/
    - assets/motions/gaming.json
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-ai.webp"
  min_sdk_android: 21
